### ISSUE TITLE
Flashing Artifacts at the Top of the Video

### ISSUE THREAD

**Issue by carycary246** [the-database/mpv-upscale-2x_animejanai#17]
Followed the instructions for setup and it seems to work, but I'm getting strange artifacts at the top of the video randomly throughout on any file that I try to run with this on the default settings. They flash for split second and disappear.

![Screenshot 2023-06-26 034243](https://github.com/the-database/mpv-upscale-2x_animejanai/assets/31323333/b2ef954b-15de-4119-a7c3-119f9e6e0c43)

**Comment by 422415** [comment]
Let me first ask if you made any changes to the mpv.conf? We have reports of this happening when using DX11 instead of Vulkan. Also are you running the latest NVIDIA driver? 

And finally, can you send a picture of the console when this is happening? You can access it by pressing the ~ key when in mpv.net. It should look like this:
<img width="870" alt="image" src="https://github.com/the-database/mpv-upscale-2x_animejanai/assets/107212291/38bfc469-41a0-4114-b958-c8c238d43eb8">

**Comment by carycary246** [comment]
I did make some changes to mpv to d3d11 in the first screenshot, but I tested again with a fresh install with default settings using vulkan and the same issue occurs. Driver version is 531.68 with RTX 4090.

Also for another data point, I tested on another pc and it does not have this issue, with both d3d11 and vulkan. Driver version 531.41 using RTX 3080. 

![Screenshot (2)](https://github.com/the-database/mpv-upscale-2x_animejanai/assets/31323333/23afb4d5-757a-4c94-98bd-9b2bb6b1fcf3)

**Comment by 422415** [comment]
If you hit Ctrl+0 to turn off AnimeJaNai does this still happen?

**Comment by carycary246** [comment]
No issues when its turned off, when I re-enable any of the presets, the artifacts will start appearing randomly.

**Comment by 422415** [comment]
Just for my sanity. Is this the same episode or have you tried multiple shows?

**Comment by carycary246** [comment]
It is the same show, and I tested several different video files and all exhibit the same sort of artifacting.

**Comment by 422415** [comment]
So the first thing that comes to mind is first try redownloading the zip file. We just had a user who had issues get fixed because his downloaded ended up getting corrupted somewhere. 

If that doesn't help. I can suggesting making sure windows is completely updated and then trying to DDU your NVIDIA driver and reinstalling to remove those two possibilities.

**Comment by carycary246** [comment]
Redownloaded the zip, DDU drivers and on latest 536.23 version now and Win11 already updated. Tested with a fresh mpv folder with new zip but getting the exact same problem.

**Comment by 422415** [comment]
Try pressing Ctrl+9 and see if you get artifacts. Ctrl+9 doesn't upscale but does go through vapoursynth. That could help us narrow it down

**Comment by hooke007** [comment]
Try `hwdec=auto-copy` or `no` first if you were using vf.

**Comment by carycary246** [comment]
Ctrl + 9 no artifacts. 

hwdec=auto-copy or no both show artifacts. 
![Screenshot (11)](https://github.com/the-database/mpv-upscale-2x_animejanai/assets/31323333/9643dc1a-a360-420a-92b8-b51270f7fd85)

**Comment by hooke007** [comment]
I can only confirm it's not from model. I could only reproduce it only when my first playback. And after removing those configs, it doesn't show any more.

**Comment by the-database** [comment]
Have you tested any other profiles besides the default or `Ctrl+9`? For example, try `Shift+3` to test `upscale-on-superultracompact4x` which will use the SuperUltraCompact model. This will generate a new TensorRT engine if you haven't used this profile before. 

You can also try `Ctrl+6` to test a profile which uses no upscaling, but does use RIFE frame interpolation. This also uses TensorRT so it allows us to test TensorRT but without running the new upscaling models.

**Comment by carycary246** [comment]
Thanks for the suggestions. I tested Ctrl 1 through 4 yesterday which all had the same issue. Will try ctrl 6 when I get home later today.

**Comment by carycary246** [comment]
Tested Ctrl + 6 and it works fine with no artifacting.

**Comment by carycary246** [comment]
Here's the log generated from your command.

```
&&&& RUNNING TensorRT.trtexec [TensorRT v8601] # .\trtexec --fp16 --onnx=..\models\animejanai\2x_AnimeJaNai_V2_SuperUltraCompact_100k.onnx --minShapes=input:1x3x8x8 --optShapes=input:1x3x1080x1920 --maxShapes=input:1x3x1080x1920 --skipInference --infStreams=4 --builderOptimizationLevel=4 --saveEngine=..\models\animejanai\2x_AnimeJaNai_V2_SuperUltraCompact_100k.engine --tacticSources=+CUDNN,-CUBLAS,-CUBLAS_LT
[06/27/2023-14:43:41] [I] === Model Options ===
[06/27/2023-14:43:41] [I] Format: ONNX
[06/27/2023-14:43:41] [I] Model: ..\models\animejanai\2x_AnimeJaNai_V2_SuperUltraCompact_100k.onnx
[06/27/2023-14:43:41] [I] Output:
[06/27/2023-14:43:41] [I] === Build Options ===
[06/27/2023-14:43:41] [I] Max batch: explicit batch
[06/27/2023-14:43:41] [I] Memory Pools: workspace: default, dlaSRAM: default, dlaLocalDRAM: default, dlaGlobalDRAM: default
[06/27/2023-14:43:41] [I] minTiming: 1
[06/27/2023-14:43:41] [I] avgTiming: 8
[06/27/2023-14:43:41] [I] Precision: FP32+FP16
[06/27/2023-14:43:41] [I] LayerPrecisions: 
[06/27/2023-14:43:41] [I] Layer Device Types: 
[06/27/2023-14:43:41] [I] Calibration: 
[06/27/2023-14:43:41] [I] Refit: Disabled
[06/27/2023-14:43:41] [I] Version Compatible: Disabled
[06/27/2023-14:43:41] [I] TensorRT runtime: full
[06/27/2023-14:43:41] [I] Lean DLL Path: 
[06/27/2023-14:43:41] [I] Tempfile Controls: { in_memory: allow, temporary: allow }
[06/27/2023-14:43:41] [I] Exclude Lean Runtime: Disabled
[06/27/2023-14:43:41] [I] Sparsity: Disabled
[06/27/2023-14:43:41] [I] Safe mode: Disabled
[06/27/2023-14:43:41] [I] Build DLA standalone loadable: Disabled
[06/27/2023-14:43:41] [I] Allow GPU fallback for DLA: Disabled
[06/27/2023-14:43:41] [I] DirectIO mode: Disabled
[06/27/2023-14:43:41] [I] Restricted mode: Disabled
[06/27/2023-14:43:41] [I] Skip inference: Enabled
[06/27/2023-14:43:41] [I] Save engine: ..\models\animejanai\2x_AnimeJaNai_V2_SuperUltraCompact_100k.engine
[06/27/2023-14:43:41] [I] Load engine: 
[06/27/2023-14:43:41] [I] Profiling verbosity: 0
[06/27/2023-14:43:41] [I] Tactic sources: cublas [OFF], cublasLt [OFF], cudnn [ON], 
[06/27/2023-14:43:41] [I] timingCacheMode: local
[06/27/2023-14:43:41] [I] timingCacheFile: 
[06/27/2023-14:43:41] [I] Heuristic: Disabled
[06/27/2023-14:43:41] [I] Preview Features: Use default preview flags.
[06/27/2023-14:43:41] [I] MaxAuxStreams: -1
[06/27/2023-14:43:41] [I] BuilderOptimizationLevel: 4
[06/27/2023-14:43:41] [I] Input(s)s format: fp32:CHW
[06/27/2023-14:43:41] [I] Output(s)s format: fp32:CHW
[06/27/2023-14:43:41] [I] Input build shape: input=1x3x8x8+1x3x1080x1920+1x3x1080x1920
[06/27/2023-14:43:41] [I] Input calibration shapes: model
[06/27/2023-14:43:41] [I] === System Options ===
[06/27/2023-14:43:41] [I] Device: 0
[06/27/2023-14:43:41] [I] DLACore: 
[06/27/2023-14:43:41] [I] Plugins:
[06/27/2023-14:43:41] [I] setPluginsToSerialize:
[06/27/2023-14:43:41] [I] dynamicPlugins:
[06/27/2023-14:43:41] [I] ignoreParsedPluginLibs: 0
[06/27/2023-14:43:41] [I] 
[06/27/2023-14:43:41] [I] === Inference Options ===
[06/27/2023-14:43:41] [I] Batch: Explicit
[06/27/2023-14:43:41] [I] Input inference shape: input=1x3x1080x1920
[06/27/2023-14:43:41] [I] Iterations: 10
[06/27/2023-14:43:41] [I] Duration: 3s (+ 200ms warm up)
[06/27/2023-14:43:41] [I] Sleep time: 0ms
[06/27/2023-14:43:41] [I] Idle time: 0ms
[06/27/2023-14:43:41] [I] Inference Streams: 4
[06/27/2023-14:43:41] [I] ExposeDMA: Disabled
[06/27/2023-14:43:41] [I] Data transfers: Enabled
[06/27/2023-14:43:41] [I] Spin-wait: Disabled
[06/27/2023-14:43:41] [I] Multithreading: Disabled
[06/27/2023-14:43:41] [I] CUDA Graph: Disabled
[06/27/2023-14:43:41] [I] Separate profiling: Disabled
[06/27/2023-14:43:41] [I] Time Deserialize: Disabled
[06/27/2023-14:43:41] [I] Time Refit: Disabled
[06/27/2023-14:43:41] [I] NVTX verbosity: 0
[06/27/2023-14:43:41] [I] Persistent Cache Ratio: 0
[06/27/2023-14:43:41] [I] Inputs:
[06/27/2023-14:43:41] [I] === Reporting Options ===
[06/27/2023-14:43:41] [I] Verbose: Disabled
[06/27/2023-14:43:41] [I] Averages: 10 inferences
[06/27/2023-14:43:41] [I] Percentiles: 90,95,99
[06/27/2023-14:43:41] [I] Dump refittable layers:Disabled
[06/27/2023-14:43:41] [I] Dump output: Disabled
[06/27/2023-14:43:41] [I] Profile: Disabled
[06/27/2023-14:43:41] [I] Export timing to JSON file: 
[06/27/2023-14:43:41] [I] Export output to JSON file: 
[06/27/2023-14:43:41] [I] Export profile to JSON file: 
[06/27/2023-14:43:41] [I] 
[06/27/2023-14:43:41] [I] === Device Information ===
[06/27/2023-14:43:41] [I] Selected Device: NVIDIA GeForce RTX 4090
[06/27/2023-14:43:41] [I] Compute Capability: 8.9
[06/27/2023-14:43:41] [I] SMs: 128
[06/27/2023-14:43:41] [I] Device Global Memory: 24563 MiB
[06/27/2023-14:43:41] [I] Shared Memory per SM: 100 KiB
[06/27/2023-14:43:41] [I] Memory Bus Width: 384 bits (ECC disabled)
[06/27/2023-14:43:41] [I] Application Compute Clock Rate: 2.52 GHz
[06/27/2023-14:43:41] [I] Application Memory Clock Rate: 10.501 GHz
[06/27/2023-14:43:41] [I] 
[06/27/2023-14:43:41] [I] Note: The application clock rates do not reflect the actual clock rates that the GPU is currently running at.
[06/27/2023-14:43:41] [I] 
[06/27/2023-14:43:41] [I] TensorRT version: 8.6.1
[06/27/2023-14:43:41] [I] Loading standard plugins
[06/27/2023-14:43:42] [I] [TRT] [MemUsageChange] Init CUDA: CPU +389, GPU +0, now: CPU 5208, GPU 1683 (MiB)
[06/27/2023-14:43:51] [I] [TRT] [MemUsageChange] Init builder kernel library: CPU +1471, GPU +266, now: CPU 7831, GPU 1949 (MiB)
[06/27/2023-14:43:51] [I] Start parsing network model.
[06/27/2023-14:43:51] [I] [TRT] ----------------------------------------------------------------
[06/27/2023-14:43:51] [I] [TRT] Input filename:   ..\models\animejanai\2x_AnimeJaNai_V2_SuperUltraCompact_100k.onnx
[06/27/2023-14:43:51] [I] [TRT] ONNX IR version:  0.0.7
[06/27/2023-14:43:51] [I] [TRT] Opset version:    14
[06/27/2023-14:43:51] [I] [TRT] Producer name:    pytorch
[06/27/2023-14:43:51] [I] [TRT] Producer version: 1.10
[06/27/2023-14:43:51] [I] [TRT] Domain:           
[06/27/2023-14:43:51] [I] [TRT] Model version:    0
[06/27/2023-14:43:51] [I] [TRT] Doc string:       
[06/27/2023-14:43:51] [I] [TRT] ----------------------------------------------------------------
[06/27/2023-14:43:51] [I] Finished parsing network model. Parse time: 0.0263579
[06/27/2023-14:43:51] [I] [TRT] Local timing cache in use. Profiling results in this builder pass will not be stored.
[06/27/2023-14:43:51] [I] [TRT] Graph optimization time: 0.0044941 seconds.
[06/27/2023-14:43:59] [I] [TRT] Detected 1 inputs and 1 output network tensors.
[06/27/2023-14:43:59] [I] [TRT] Total Host Persistent Memory: 29920
[06/27/2023-14:43:59] [I] [TRT] Total Device Persistent Memory: 0
[06/27/2023-14:43:59] [I] [TRT] Total Scratch Memory: 0
[06/27/2023-14:43:59] [I] [TRT] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 0 MiB, GPU 512 MiB
[06/27/2023-14:43:59] [I] [TRT] [BlockAssignment] Started assigning block shifts. This will take 24 steps to complete.
[06/27/2023-14:43:59] [I] [TRT] [BlockAssignment] Algorithm ShiftNTopDown took 0.0848ms to assign 4 blocks to 24 nodes requiring 447898112 bytes.
[06/27/2023-14:43:59] [I] [TRT] Total Activation Memory: 447897600
[06/27/2023-14:43:59] [I] [TRT] Local timing cache in use. Profiling results in this builder pass will not be stored.
[06/27/2023-14:43:59] [I] [TRT] Graph optimization time: 0.0015638 seconds.
[06/27/2023-14:44:39] [I] [TRT] Detected 1 inputs and 1 output network tensors.
[06/27/2023-14:44:39] [I] [TRT] Total Host Persistent Memory: 56416
[06/27/2023-14:44:39] [I] [TRT] Total Device Persistent Memory: 0
[06/27/2023-14:44:39] [I] [TRT] Total Scratch Memory: 0
[06/27/2023-14:44:39] [I] [TRT] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 0 MiB, GPU 3042 MiB
[06/27/2023-14:44:39] [I] [TRT] [BlockAssignment] Started assigning block shifts. This will take 34 steps to complete.
[06/27/2023-14:44:39] [I] [TRT] [BlockAssignment] Algorithm ShiftNTopDown took 0.184ms to assign 4 blocks to 34 nodes requiring 248832512 bytes.
[06/27/2023-14:44:39] [I] [TRT] Total Activation Memory: 248832512
[06/27/2023-14:44:39] [I] [TRT] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +0, GPU +4, now: CPU 0, GPU 4 (MiB)
[06/27/2023-14:44:39] [I] Engine built in 58.2441 sec.
[06/27/2023-14:44:39] [I] [TRT] Loaded engine size: 0 MiB
[06/27/2023-14:44:39] [I] [TRT] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
[06/27/2023-14:44:39] [I] Engine deserialized in 0.0037349 sec.
[06/27/2023-14:44:39] [I] Skipped inference phase since --skipInference is added.
&&&& PASSED TensorRT.trtexec [TensorRT v8601] # .\trtexec --fp16 --onnx=..\models\animejanai\2x_AnimeJaNai_V2_SuperUltraCompact_100k.onnx --minShapes=input:1x3x8x8 --optShapes=input:1x3x1080x1920 --maxShapes=input:1x3x1080x1920 --skipInference --infStreams=4 --builderOptimizationLevel=4 --saveEngine=..\models\animejanai\2x_AnimeJaNai_V2_SuperUltraCompact_100k.engine --tacticSources=+CUDNN,-CUBLAS,-CUBLAS_LT

```

**Comment by the-database** [comment]
Thanks, I don't see any issues with the engine creation. Let's try to pin down whether the issue is with these upscaling models, or if it's specific to mpv without the upscaling models. Please open `mpv-upscale-2x_animejanai\portable_config\shaders\animejanai_v2.conf`, scroll down to `[slot_7]` and add this line:

```
chain_1_model_1_resize_height_before_upscale=2160
```

So that part of your config file should look like this after editing:
```
# ===============================================================================================
# Slot 7
# Enter description here.
# ===============================================================================================
[slot_7]
chain_1_model_1_resize_height_before_upscale=2160

# End of Slot 7 config

# ===============================================================================================
# Slot 8
# Enter description here.
# ===============================================================================================
[slot_8]



# End of Slot 8 config
```

Then open mpv and enter Ctrl+7 to activate the profile we just set up. This doesn't perform any upscaling with TensorRT, but it resizes the video to 4k using vapoursynth. Does this result in the same artifacts?

**Comment by carycary246** [comment]
Yes that does result in the same artifacts.

![Screenshot (12)](https://github.com/the-database/mpv-upscale-2x_animejanai/assets/31323333/522c87ab-101f-47e3-a0ee-6baad8e7f31c)

**Comment by the-database** [comment]
OK, so that rules out TensorRT or the upscaling models specifically causing the issue. The issue could be mpv, Vapoursynth, or the interaction between the two. 

Have you tried using mpv.exe instead of mpvnet.exe? I doubt it helps but might as well make sure. 

I published a new pre-release, version 2.0.1. Could you please update to 2.0.1, and then use the encoding scripts to try encoding a 1080p video upscaled to 4k? This will test Vapoursynth without mpv. Then try playing that video in mpv as well as a different player, and see if artifacts show up in either scenario. 

To use the encoding script, edit `mpv-upscale-2x_animejanai\portable_config\shaders\animejanai_v2_encode_single.bat` and set the input_video to the full path of the video to encode, and set the output_video to where you want to save the encoded file. To save time suggest using a short video file if you have one.

**Comment by carycary246** [comment]
Updated to the version 2.0.1 same issue with both mpv and mpvnet. Did a short 3min encoding of the same file I was testing with and the encoded file does show the same artifacts, tested with a default mpv and windows media player. Since it is encoded, the artifacts show up at the exact same spots in both players.

**Comment by the-database** [comment]
Thanks for testing that. Let's try and narrow the issue down further. 

Save the following block of text to a new file called `test.vpy`, and place this file at this path: `\mpv-upscale-2x_animejanai\portable_config\shaders`

```
import vapoursynth as vs

clip = vs.core.ffms2.Source(source=r"benchmarks\1920x1080.mp4")

fmt_in = clip.format.id

clip = vs.core.resize.Spline36(clip, format=vs.RGBH, matrix_in_s='709',
                                              width=3840,
                                              height=2160)

clip = vs.core.resize.Spline36(clip, format=fmt_in, matrix_s='709', range=1)

clip.set_output()
```

Then open a cmd command prompt (not powershell), change directory to same shaders folder where you placed `test.vpy` and then run this command: `..\..\VSPipe.exe -c y4m ./test.vpy - | ..\..\mpv -`

Give it a few seconds, and it should play a black video in mpv, which vapoursynth has resized from 1920x1080 to 3840x2160. This is no longer using the animejanai vapoursynth script, but a much simpler script. Do the artifacts still appear?

**Comment by carycary246** [comment]
Yes the artifacts do still appear running this script.

![Screenshot (13)](https://github.com/the-database/mpv-upscale-2x_animejanai/assets/31323333/378606c0-b362-42bd-8a33-114a1c08a796)

**Comment by the-database** [comment]
Thanks. I forgot to mention, while playing the video please press Ctrl+0 to disable the animejanai profile as well. After doing that the Filters section at the bottom of the `t` output should no longer appear. Do the artifacts still appear after that change?

**Comment by carycary246** [comment]
Turned off the filters and artifacts still do appear but not as prominent as before.

![image](https://github.com/the-database/mpv-upscale-2x_animejanai/assets/31323333/89c77b68-9ffa-48d9-9feb-a76f86035cfa)

**Comment by the-database** [comment]
Thanks for confirming that. I also have an older build which uses Vapoursynth R61 instead of the latest R63: https://mega.nz/file/1h8ExDZZ#s95_jyaRlUWO52UcwSwFjoTX-X7ysSLBhjzXXrsO2yU

Please download and try playing any of your videos with it. Make sure upscaling is enabled with `t` and enable it with `Ctrl+1` if needed. Do the artifacts appear? 

Also, what is the resolution of your display? Is it exactly 3840x2160?

**Comment by carycary246** [comment]
I think that fixed the issue, no more artifacts using that older version of vapoursynth and yes resolution of display is exactly 3840x2160. Will check a few more files but seems good so far.

**Comment by the-database** [comment]
Thanks. I reported this issue to VapourSynth: https://github.com/vapoursynth/vapoursynth/issues/975

The build I shared is a bit outdated, I'll prepare a new official release using R61 soon.

**Comment by the-database** [comment]
I prepared a new prerelease, version 2.0.2. Please test it out and let me know if it solves your issue. This uses a custom build of R63 which should fix the issue according to the information in the VapourSynth issue above. You can either use the update package to update your 2.0.1 build or redownload the standalone package to start from scratch. 

Also, which CPU are you using on your PC which has the artifact issue, as well as the PC that doesn't have any issues? It seems the difference in CPU is what's causing the issue on some PCs and not others.

**Comment by carycary246** [comment]
Perfect, thanks. Updated with the new build and it does appear to resolve the artifact issue.

CPU on the pc with the issue is using Ryzen 7800x3D. The pc without the issue is using Ryzen 5900x.

**Comment by the-database** [comment]
Thanks for confirming, so this issue was only affecting users with AMD 7000 series CPUs. Closing the issue as it's confirmed to be fixed in 2.0.2.
